language: haskell
sudo: false

services:
  - mysql

install:
  - mysql -uroot -e "CREATE DATABASE hatohol;"
  - mysql -uroot -e "CREATE USER 'hatohol'@'localhost' IDENTIFIED BY 'hatohol';"
  - mysql -uroot -e "GRANT ALL PRIVILEGES ON hatohol.* TO 'hatohol'@'localhost';"
  - mysql -uroot hatohol < ./fixture/hatohol.sql
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - stack --skip-ghc-check setup
  - stack +RTS -N2 -RTS --no-terminal build

script:
  - stack +RTS -N2 -RTS --no-terminal test